# Generated by Django 4.1.5 on 2023-07-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='news_article',
        ),
    ]
