# Generated by Django 4.1.5 on 2023-07-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busschedule',
            old_name='img',
            new_name='image',
        ),
    ]
