# Generated by Django 4.1.5 on 2023-07-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_rename_images_busschedule_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busschedule',
            table='schedules_bus',
        ),
        migrations.AlterModelTable(
            name='churchschedule',
            table='schedules_church',
        ),
    ]
