# Generated by Django 4.1.5 on 2023-07-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_busschedule_table_alter_churchschedule_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='churchscheduleimage',
            table='schedules_church_images',
        ),
    ]
